name: 'Config parser'
description: 'Parse the publish config file'
inputs:
  publish-config:
    description: 'Path to the publish config file'
    required: true
    default: 'publish-config.yml'

outputs:
  publisher-url:
    value: ${{ steps.config-parser.outputs.publisher-url }}
    description: "URL of the svn repo"
  publisher-path:
    value: ${{ steps.config-parser.outputs.publisher-path }}
    description: "Path to the svn repo"
  checks-svn:
    value: ${{ steps.config-parser.outputs.checks-svn }}
    description: "Config for svn checks"
  checks-checksum:
    value: ${{ steps.config-parser.outputs.checks-checksum }}
    description: "Config for checksum checks"
  checks-signature:
    value: ${{ steps.config-parser.outputs.checks-signature }}
    description: "Config for signature checks"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: "Config parser"
      shell: bash
      id: config-parser
      env:
        PUBLISH_CONFIG_FILE: ${{ inputs.publish-config }}
        PUBLISH_CONFIG_SCHEMA: ${{ github.action_path }}/publish-config-schema.yml.schema.json
      run: |
        python3 -m pip install uv
        uv run $GITHUB_ACTION_PATH/config_parser.py