name: "Checksum Validator"
description: "Validate checksum of packages"

inputs:
  checksum-config:
    description: >
      Json config for checksum, it contains all the information required to validate the checksum of the packages.
      It does validation for the checksum of the packages, all the packages should have checksum 
      files and hashed with sha algorithm.
    required: true

  temp-dir:
    description: >
      Checkout directory of svn repo, this is used to checkout the svn repo.
    required: false
    default: "asf-dist"

  repo-path:
    description: >
      Path to the svn repo. Lets say to publish the packages from the dev folder.
      eg: svn repo structure is https://dist.apache.org/repos/dist/
        dev/airflow/providers
        release/airflow/providers
      now to publish the packages from dev providers folder, set url and path like below in the release-config.yml
      url: https://dist.apache.org/repos/dist/dev/airflow
      repo-path: providers/
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: "Check sum validation"
      shell: bash
      id: check-sum
      env:
        REPO_PATH: ${{ inputs.repo-path }}
        CHECK_SUM_CONFIG: ${{ inputs.checksum-config }}
      run: |
        python3 -m pip install uv
        uv run $GITHUB_ACTION_PATH/checksum_check.py
      working-directory: "./${{ inputs.temp-dir }}/${{ inputs.repo-path }}"