project:
    Name: gh-svn-pypi-publisher
    Description: Example project for publishing to PyPI

publishers:
    name: providers
    url: https://gh-svn-pypi-publisher/
    path: "airflow/providers/"
    version_pattern: '^(.*?)-(rc\d+-)?\d+'
    extensions:
      - .tar.gz
      - .tar.gz.asc
      - .tar.gz.sha512
      - -py3-none-any.whl
      - -py3-none-any.whl.asc
      - -py3-none-any.whl.sha512
    rules:
      svn-check:
          name: "SVN Check"
          type: "svn"
          enabled: "false"
      checksum-check:
            name: "SHA512 Check"
            type: "512"
            enabled: "false"
      signature-check:
            name: "Signature Check"
            enabled: "false"
            script: "/home/runner/work/gh-svn-pypi-publisher/gh-svn-pypi-publisher/scripts/signature_check.sh"
            keys: "https://dist.apache.org/repos/dist/release/airflow/KEYS"
