name: "Svn Validator"
description: "Validate svn files"

inputs:
  svn-config:
    description: > 
      Json config for svn, it contains all the information required to validate the svn files.
      It does validation for the svn files, like checking the file extension, package names.
    required: true
  temp-dir:
    description: >
      Checkout directory of svn repo, this is used to checkout the svn repo.
    required: false
    default: "asf-dist"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: "SVN validation"
      shell: bash
      id: svn-check
      env:
        SVN_CHECK_CONFIG: ${{ inputs.svn-config }}
      run: |
        python3 -m pip install uv
        uv run $GITHUB_ACTION_PATH/svn_check.py
      working-directory: "./${{ inputs.temp-dir }}/${{ inputs.repo-path }}"