name: "Svn Validator"
description: "Validate svn files"

inputs:
  svn-config:
    description: > 
      Json config for svn, it contains all the information required to validate the svn files.
      It does validation for the svn files, like checking the file extension, package names.
    required: true
  temp-dir:
    description: >
      Checkout directory of svn repo, this is used to checkout the svn repo.
    required: false
    default: "asf-dist"
  repo-url:
    description: >
      URL of the svn repo ex: https://dist.apache.org/repos/dist/release/airflow/
      this is used to checkout the svn repo.
    required: true
  repo-path:
    description: >
      Path to the svn repo. Lets say to publish the packages from the dev folder.
      eg: svn repo structure is https://dist.apache.org/repos/dist/
        dev/airflow/providers
        release/airflow/providers
      now to publish the packages from dev providers folder, set url and path like below in the release-config.yml
      url: https://dist.apache.org/repos/dist/dev/airflow
      repo-path: providers/
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: "SVN validation"
      shell: bash
      id: svn-check
      env:
        SVN_CHECK_CONFIG: ${{ inputs.svn-config }}
      run: |
        python3 -m pip install uv
        uv run $GITHUB_ACTION_PATH/svn_check.py
      working-directory: "./${{ inputs.temp-dir }}/${{ inputs.repo-path }}"