name: 'Signature Validator'
description: 'Validate signature of packages'
inputs:
  signature-config:
    description: 'Json config for signature validation'
    required: true
  temp-dir:
    description: 'Checkout directory of svn repo'
    required: false
    default: 'temp-svn-repo'
  repo-path:
    description: 'Path to the svn repo ex: airflow/providers/'
    required: true
  repo-url:
    description: 'URL of the svn repo ex: https://dist.apache.org/repos/dist/release/airflow/'
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: "Signature validation"
      shell: bash
      id: signature-check
      env:
        SIGNATURE_CHECK_CONFIG: ${{ inputs.signature-config }}
      run: |
        python3 -m pip install uv
        uv run $GITHUB_ACTION_PATH/signature_check.py
      working-directory: "./${{ inputs.temp-dir }}/${{ inputs.repo-path }}"