name: 'Signature Validator'
description: 'Validate signature of packages'
inputs:
  signature-config:
    description: >
      Json config for signature validation, it contains all the information required to validate the signature of the packages.
      It does validation for the signature of the packages, all the packages should have valid.
    required: true
  temp-dir:
    description: >
      Checkout directory of svn repo, this is used to checkout the svn repo.
    required: false
    default: "asf-dist"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: "Signature validation"
      shell: bash
      id: signature-check
      env:
        SIGNATURE_CHECK_CONFIG: ${{ inputs.signature-config }}
      run: |
        python3 -m pip install uv
        uv run $GITHUB_ACTION_PATH/signature_check.py
      working-directory: "./${{ inputs.temp-dir }}/${{ inputs.repo-path }}"