
name: Release Publisher
on:
  workflow_dispatch:

jobs:
  parser:
    runs-on: ubuntu-latest
    outputs:
        pub_config: ${{ toJson(fromJSON(steps.config-parser.outputs.pub_config)) }}
    steps:
     - name: Checkout Code
       uses: actions/checkout@v3
     - name: Setup Python
       uses: actions/setup-python@v4
       with:
          python-version: '3.9'
     - name: "Config parser"
       id: config-parser
       run: |
            python3 -m pip install pyyaml
            python3 config_parser.py "publish-config.yml"

     - name: Checkout SVN
       env:
         repo_url: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.url }}
       run: |
         echo "svn-check"
         svn co $repo_url
         ls -lthr
         echo "$GITHUB_WORKSPACE"
         echo $PWD
         cd airflow/providers && pwd
     - name: SVN check
       env:
         extensions: ${{ toJson(fromJSON(steps.config-parser.outputs.pub_config).packages.extensions) }}
         path: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.path }}
         name: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.rules.svn-check.name }}
         version_pattern: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.version_pattern }}
       working-directory: ./${{ fromJSON(steps.config-parser.outputs.pub_config).packages.path }}
       run: |
            echo "Verifying $name"
            echo "$extensions"
            python3 /home/runner/work/example-pub/example-pub/svn_checker.py "$extensions" $version_pattern

     - name: Checksum check
       env:
         name: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.rules.checksum-check.name }}
         type: ${{ fromJSON(steps.config-parser.outputs.pub_config).packages.rules.checksum-check.type }}
       working-directory: ./${{ fromJSON(steps.config-parser.outputs.pub_config).packages.path }}
       run: |
            echo "Verifying $name"
            echo $PWD
            chmod +x /home/runner/work/example-pub/example-pub/check-sum.sh
            /home/runner/work/example-pub/example-pub/check-sum.sh "$type"
