name: GH pypi publish
description: 'Publish to PyPI'

on:
  workflow_dispatch:
    inputs:
      publish-config:
        description: 'Path to the publish config file'
        required: true
        default: 'publish-config.yml'
      temp-dir:
        description: 'Temporary directory to checkout svn repo'
        required: false
        default: 'temp-svn-repo'
      mode:
        description: 'Mode to run the action'
        required: false
        default: 'verify'

jobs:
  gh-action-pypi-publish:
    runs-on: ubuntu-latest
    environment: test
    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Setup Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.11'

     - name: "Config parser"
       id: config-parser
       uses: ./read-config
       with:
        publish-config: ${{ inputs.publish-config }}

     - name: "Checkout svn ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}"
       id: "svn-checkout"
       uses: ./init
       with:
         temp-dir: ${{ inputs.temp-dir }}
         repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
         repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path) }}

     - name: "Svn check"
       id: "svn-check"
       uses: ./svn
       with:
        svn-config: ${{ steps.config-parser.outputs.checks-svn }}
        repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
        repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path) }}

     - name: "Checksum check"
       id: "checksum-check"
       uses: ./checksum
       with:
        checksum-config: ${{ steps.config-parser.outputs.checks-checksum }}
        repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
        repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path) }}

     - name: "Signature check"
       id: "signature-check"
       uses: ./signature
       with:
        signature-config: ${{ steps.config-parser.outputs.checks-signature }}
        repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
        repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path) }}