name: Tes gh-svn-pypi-publisher
description: "Publish to PyPI"

on:
  workflow_dispatch:
    inputs:
      publish-config:
        description: "Path to the publish config file"
        required: true
        default: "release-config.yml"
      temp-dir:
        description: >
          Checkout directory of svn repo, this is used to checkout the svn repo.
        required: false
        default: "asf-dist"
      mode:
        description: "Mode to run the action"
        required: false
        default: "VERIFY"

jobs:
  gh-action-pypi-publish:
    runs-on: ubuntu-latest
    environment: test
    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Setup Python
       uses: actions/setup-python@v4
       with:
         python-version: "3.11"

     - name: "Config parser"
       id: config-parser
       uses: ./read-config
       with:
        publish-config: ${{ inputs.publish-config }}

     - name: "Checkout svn ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}"
       id: "svn-checkout"
       uses: ./init
       with:
         temp-dir: ${{ inputs.temp-dir }}
         repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
         repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path) }}

     - name: "Svn check"
       id: "svn-check"
       uses: ./svn
       with:
        svn-config: ${{ steps.config-parser.outputs.checks-svn }}
        repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
        repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path) }}

     - name: "Checksum check"
       id: "checksum-check"
       uses: ./checksum
       with:
        checksum-config: ${{ steps.config-parser.outputs.checks-checksum }}
        repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
        repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path) }}

     - name: "Signature check"
       id: "signature-check"
       uses: ./signature
       with:
        signature-config: ${{ steps.config-parser.outputs.checks-signature }}
        repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
        repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path) }}

     - name: "Find ${{ steps.config-parser.outputs.publisher-name }} packages"
       permissions:
         id-token: write
       id: "publish-to-pypi"
       uses: ./publish
       with:
        publish-config: ${{ steps.config-parser.outputs.checks-publish }}
        repo-url: ${{ fromJSON(steps.config-parser.outputs.publisher-url) }}
        repo-path: ${{ fromJSON(steps.config-parser.outputs.publisher-path) }}
        temp-dir: ${{ inputs.temp-dir }}
        mode: ${{ inputs.mode }}
        publisher-name: ${{ fromJSON(steps.config-parser.outputs.publisher-name) }}

     - name: "Download release distributions for ${{ steps.config-parser.outputs.publisher-name }}"
       uses: actions/download-artifact@v4
       with:
         merge-multiple: true
         path: ./dist

     - name: "Publishing ${{ steps.config-parser.outputs.publisher-name }} to PyPI"
       uses: pypa/gh-action-pypi-publish@release/v1
       if: inputs.mode == 'RELEASE'
       with:
         packages-dir: "./dist"